export const SECTEUR_EMOJI: Record<string, string> = {
  ECOLE_PRIMAIRE: "🏫",
  ECOLE_SECONDAIRE: "🏫",
  ECOLE_SPECIALISEE: "🎓",
  HOPITAL: "🏥",
  HOPITAL_PSY: "🧠",
  SERVICE_SANTE_MENTALE: "💬",
  MAISON_SOIN_PSY: "🏠",
  AIDE_JEUNESSE: "👶",
  PRISON: "🔒",
  IPPJ_FERME: "🔐",
  IPPJ_OUVERT: "🚪",
  SERVICE_LOGEMENT_ADAPTE: "🏘️",
  INTERNAT: "🛏️",
  ECOLE_DEVOIRS: "📚",
  MAISON_JEUNE: "🏡",
  MAISON_SOIN_REPOS: "🌿",
  SANS_CHEZ_SOIRISME: "⛺",
  CENTRE_HEBERGEMENT: "🏘️",
  CRECHE: "🍼",
  EMA: "🚐",
  CCMD: "👥",
  PERISCOLAIRE: "⛹️",
  SRG: "🏠",
  SRU: "🚨",
  SRJ: "🧒",
  AMO: "🤝",
  MECS: "🏡",
  IME: "♿",
  MAS: "🌸",
  CHRS: "🏘️",
  CPAS_ACTION: "🏛️",
  CENTRE_JOUR: "☀️",
};

export const COMMUNES_BRUXELLES = [
  "Anderlecht",
  "Auderghem",
  "Berchem-Sainte-Agathe",
  "Bruxelles (Ville)",
  "Etterbeek",
  "Evere",
  "Forest",
  "Ganshoren",
  "Ixelles",
  "Jette",
  "Koekelberg",
  "Molenbeek-Saint-Jean",
  "Saint-Gilles",
  "Saint-Josse-ten-Noode",
  "Schaerbeek",
  "Uccle",
  "Watermael-Boitsfort",
  "Woluwe-Saint-Lambert",
  "Woluwe-Saint-Pierre",
];

export const COMMUNES_NAMUR = [
  "Andenne",
  "Anhée",
  "Assesse",
  "Beauraing",
  "Bièvre",
  "Ciney",
  "Couvin",
  "Dinant",
  "Doische",
  "Éghezée",
  "Fernelmont",
  "Floreffe",
  "Florennes",
  "Fosses-la-Ville",
  "Gedinne",
  "Gembloux",
  "Gesves",
  "Hamois",
  "Hastière",
  "Havelange",
  "Houyet",
  "Jemeppe-sur-Sambre",
  "La Bruyère",
  "Mettet",
  "Namur",
  "Ohey",
  "Onhaye",
  "Philippeville",
  "Profondeville",
  "Rochefort",
  "Sambreville",
  "Sombreffe",
  "Somme-Leuze",
  "Viroinval",
  "Walcourt",
  "Yvoir",
];

export const PUBLIC_TYPES: Record<string, string> = {
  ECOLE_PRIMAIRE: "Établissement scolaire primaire",
  ECOLE_SECONDAIRE: "Établissement scolaire secondaire",
  ECOLE_SPECIALISEE: "Établissement scolaire spécialisée",
  HOPITAL: "Hôpital",
  HOPITAL_PSY: "Hôpital psychiatrique",
  SERVICE_SANTE_MENTALE: "Service de santé mentale",
  MAISON_SOIN_PSY: "Maison de soin psychiatrique",
  AIDE_JEUNESSE: "Aide à la jeunesse",
  PRISON: "Prison",
  IPPJ_FERME: "IPPJ fermé",
  IPPJ_OUVERT: "IPPJ ouvert",
  SERVICE_LOGEMENT_ADAPTE: "Service de logement adapté",
  INTERNAT: "Internat",
  ECOLE_DEVOIRS: "École de devoirs",
  MAISON_JEUNE: "Maison de jeune (MJ)",
  MAISON_SOIN_REPOS: "Maison de soin et de repos",
  SANS_CHEZ_SOIRISME: "Sans-chez-soirisme",
  CENTRE_HEBERGEMENT: "Centre d'hébergement",
  CRECHE: "Crèche",
  EMA: "Équipe mobile d'accompagnement (EMA)",
  CCMD: "Centre communautaire pour mineurs dessaisis (CCMD)",
  PERISCOLAIRE: "Périscolaire",
  SRG: "Service résidentiel généraux (SRG)",
  SRU: "Service résidentiel d'urgence (SRU)",
  SRJ: "Service résidentiel pour jeunes (SRJ)",
  AMO: "Aide en milieu ouvert (AMO)",
  MECS: "Maisons d'enfants à caractère social et foyers d'accueil (MECS)",
  IME: "Instituts médico-éducatifs (IME)",
  MAS: "Maisons d'accueil spécialisées (MAS)",
  CHRS: "Centres d'hébergement et de réinsertion sociale (CHRS)",
  CPAS_ACTION: "Centre public d'action sociale (CPAS)",
  CENTRE_JOUR: "Centre de jour",
};

export const HEBERGEMENTS: Record<string, string> = {
  TYPE_1: "Type 1",
  TYPE_2: "Type 2",
  TYPE_3: "Type 3",
  TYPE_4: "Type 4",
  TYPE_5: "Type 5",
  TYPE_6: "Type 6",
  TYPE_7: "Type 7",
  TYPE_8: "Type 8",
  TYPE_9: "Type 9",
  TYPE_10: "Type 10",
  AUTISME: "Autisme",
  TRISOMIE_21: "Trisomie 21",
  PSYCHIATRIE: "Psychiatrie",
  HANDICAP_MOTEUR: "Handicap moteur",
  SENIORS: "Séniors et aînés",
  AFFAIRE_SOCIAL: "Affaire social",
  EDUCATION_CULTURE: "Éducation, culture",
  TRAVAIL_EMPLOI: "Travail, emploi",
  ENFANCE_JEUNESSE: "Enfance, jeunesse",
  FAMILLE: "Famille",
  IMMIGRATION: "Immigration et intégration",
  JUSTICE_DROIT: "Justice et droit",
  SANTE: "Santé",
  SANTE_MENTALE: "Santé mentale",
  ENFANTS_0_6: "Enfants 0 à 6 ans",
  ENFANTS_6_10: "Enfants 6 à 10 ans",
  ADOLESCENT: "Adolescents 10 à 18 ans",
  ADULTES: "Adultes",
};

export const STUDY_YEARS: Record<string, string> = {
  SEC_4: "4ème Secondaire",
  SEC_5: "5ème Secondaire",
  SEC_6: "6ème Secondaire",
  HE_1: "1ère Haute École",
  HE_2: "2ème Haute École",
  HE_3: "3ème Haute École",
  MASTER_1: "1ère Master",
  MASTER_2: "2ème Master",
};

export const ORGANISMES: Record<string, string> = {
  AVIQ: "AVIQ",
  ONE: "ONE",
  COCOF: "COCOF",
  CPAS: "CPAS",
  SECTEUR_PRIVE: "Secteur privé",
  AUTRE: "Autre",
};
